version: '3.8'

services:
  db:
    image: postgres:13
    container_name: document_analysis_db
    environment:
      POSTGRES_DB: document_analysis_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: document_analysis_backend
    environment:
      SECRET_KEY: ${SECRET_KEY}
      DATABASE_URL: postgresql://user:password@db:5432/document_analysis_db
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      UPLOAD_FOLDER: /app/uploads
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_PUBLIC_KEY: ${STRIPE_PUBLIC_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
    depends_on:
      - db
    command: flask run --host=0.0.0.0 --port=5000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: document_analysis_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    command: npm run dev

volumes:
  db_data:
  uploads_data: